--- 
blogs:
- jekyll_repo: /home/wwwroot/blog
  source_dir: /home/wwwroot/blog/source
  pop_server: pop.gmail.com
  pop_user: jmail2octo@gmail.com
  pop_password: linpengxuan
  secret: abcd1234
  markup: markdown
  site_url: http://colors4.us
  commit_after_save: true
